#production
deployment:
  user: root
  from: ./
#  source:
#    type: git
#    repository: git://github.com/andres-montanez/Zend-Framework-Twig-example-app.git
#    from: production
#    temporal: /tmp/myAppClone
  to: /var/www/vhosts/example.com/www
  excludes:
    - application/data/cache/twig/*
# git-rebase-defaults: required to do mage deploygit command (git rebasing deploy strategy)
# remote: git repo origin to be used in host to fetch from
# branch: git branch to be rebased / deployed in host
git-rebase-defaults:
  remote: origin
  branch: master
releases:
  enabled: true
  max: 5
  symlink: current
  directory: releases
hosts:
  s01.example.com:22:
    deployment:
      user: nobody
  s02.example.com:
    deployment:
      user: toor
      to: /home/web/public
    releases:
      max: 10
    tasks:
      on-deploy:
        - privileges
  - s03.example.com
tasks:
  pre-deploy:
    - scm/update
  on-deploy:
#    - symfony2/cache-warmup: {env: prod}
    - privileges
    - sampleTask
    - sampleTaskRollbackAware
  #post-deploy: