#staging
deployment:
  user: root
  from: ./
  to: /var/www/
  scm:
    branch: master
  # deployment_git: required to do mage deploygit command (git rebasing deploy strategy)
  # remote: git repo origin to be used in host to fetch from
  # branch: git branch to be rebased / deployed in host
  deployment_git:
    remote: origin
    branch: master
releases:
  enabled: true
  max: 5
  symlink: current
  directory: releases
hosts:
  - localhost
#  - dbserver
tasks:
  pre-deploy:
    - sampleTask
#    - failTask
    - scm/update
  on-deploy:
    - privileges
    - sampleTask
    - sampleTaskRollbackAware
    - taskWithParameters:
        booleanOption: true
    - taskWithParameters
  post-release:
#    - sampleTask
  post-deploy:
    - sampleTask
